Week10 in class examples update.
Chrome is being Janky. Need to go and search up how to fix: "VM139 main.js:1 ERROR NotSupportedError: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at jt.attachShadow (polyfills.js:1:4057)
    at jt.attachShadow (polyfills.js:1:4057)
    at jt.attachShadow (polyfills.js:1:4057)
    at _e.attachShadow (polyfills.js:1:7378)
    at jt.attachShadow (polyfills.js:1:4057)
    at jt.attachShadow (polyfills.js:1:4057)
    at _e.attachShadow (polyfills.js:1:7378)
    at new j1e (main.js:1:201720)
    at n.getOrCreateRenderer (main.js:1:199863)
    at n.createRenderer (main.js:1:199499)" issues. See private discord server.